[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
assert_cmd = "2"
async-trait = "0.1"
axum = "0.8"
base64 = "0.22"
bytes = "1"
clap = "4"
criterion = "0.8"
cucumber = "0.23"
derive_more = "2"
dhat = "0.3"
dirs = "6.0"
dotenvy = "0.15"
futures = "0.3"
garde = "0.23"
getset = "0.1"
hex = "0.4"
http = "1"
http-body = "1"
http-body-util = "0.1"
humantime-serde = "1.1"
hyper = "1.1"
hyper-util = "0.1"
lazy_static = "1"
md-5 = "0.11"
mime_guess = "2.0"
moka = "0.12"
opentelemetry = "0.32"
opentelemetry-otlp = "0.32"
opentelemetry_sdk = "0.32"
papaya = "0.2"
parse-display = "0.11"
predicates = "3"
prometheus = "0.14"
proptest = "1.11"
redb = "4.2"
rustix = "1.1"
rustls-pemfile = "2.2"
s3s = "0.15"
secrecy = "0.10"
serde = "1"
serde_ignored = "0.1"
serde_json = "1.0"
sha1 = "0.11"
smart-default = "0.7"
strict-path = "0.2"
tempfile = "3.27"
thiserror = "2.0"
thread-priority = "3.1"
time = "0.3"
tokio = "1"
tokio-rustls = "0.26"
tokio-util = "0.7"
tower = "0.5"
toml = "1.1"
tracing = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = "0.3"
url = "2"
utoipa = "5.5"
uuid = "1"
winapi-util = "0.1"
windows-sys = "0.61"

tinio = { path = "crates/tinio" }
tinio-api = { path = "crates/tinio-api", default-features = false }
tinio-cli = { path = "crates/tinio-cli", default-features = false }
tinio-config = { path = "crates/tinio-config" }
tinio-core = { path = "crates/tinio-core" }
tinio-fs = { path = "crates/tinio-fs" }
tinio-mem = { path = "crates/tinio-mem" }
tinio-server = { path = "crates/tinio-server", default-features = false }
tinio-util = { path = "crates/tinio-util" }
